/**
 * @fileoverview Tests for config/context-file-generator module.
 *
 * Validates that GEMINI.md and AGENTS.md are correctly derived from
 * CLAUDE.md content with appropriate text replacements, section stripping,
 * and auto-generated headers.
 *
 * Note: COPILOT.md is NOT generated — Copilot CLI natively reads
 * AGENTS.md, CLAUDE.md, and GEMINI.md.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { generateGeminiMd, generateAgentsMd } from '../../src/config/context-file-generator.js';

// Sample CLAUDE.md content that exercises all replacement paths
const SAMPLE_CLAUDE_MD = [
  '# MyProject',
  '',
  '## Project Context',
  '- **IDE**: Claude Code recommended',
  '- **Config**: CLAUDE.md for project context',
  '- **Local**: CLAUDE.local.md for runtime state',
  '- **Commands**: stored in .claude/commands/',
  '- **Rules**: loaded from .claude/rules/chati/',
  '- **MCP config**: .claude/mcp.json',
  '',
  '## How to Run',
  'Use `claude --print` or `claude -p` to run non-interactively.',
  '',
  '## Hooks',
  'The framework uses 6 hooks for governance:',
  '- mode-governance',
  '- constitution-guard',
  '- **Hooks**: 6 Claude Code hooks active',
  '',
  '## Hook System',
  'Hooks intercept events and enforce rules.',
  'They run before and after agent execution.',
  '',
  '## Pipeline',
  'DISCOVER -> PLAN -> BUILD -> DEPLOY',
  '',
  '---',
  '_Auto-updated by chati.dev_',
].join('\n');

// ---------------------------------------------------------------------------
// generateGeminiMd
// ---------------------------------------------------------------------------

describe('generateGeminiMd', () => {
  it('replaces Claude Code with Gemini CLI', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('Claude Code'), 'Should not contain "Claude Code"');
    assert.ok(result.includes('Gemini CLI'), 'Should contain "Gemini CLI"');
  });

  it('replaces CLAUDE.md with GEMINI.md', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    // The header legitimately contains "from CLAUDE.md" — strip it before checking
    const body = result.replace(/^<!--.*-->\n\n?/, '');
    assert.ok(!body.includes('CLAUDE.md'), 'Body should not contain "CLAUDE.md"');
    assert.ok(body.includes('GEMINI.md'), 'Body should contain "GEMINI.md"');
  });

  it('replaces .claude/commands/ with .gemini/commands/', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/commands/'), 'Should not contain ".claude/commands/"');
    assert.ok(result.includes('.gemini/commands/'), 'Should contain ".gemini/commands/"');
  });

  it('adds auto-generated header', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.startsWith('<!-- Auto-generated by chati.dev from CLAUDE.md'));
    assert.ok(result.includes('do not edit manually'));
  });

  it('replaces .claude/rules/ with chati.dev/context/ (Gemini has no rules/)', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/rules/'), 'Should not contain ".claude/rules/"');
    assert.ok(result.includes('chati.dev/context/'), 'Should contain "chati.dev/context/"');
  });

  it('replaces .claude/mcp.json with .gemini/settings.json', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/mcp.json'), 'Should not contain ".claude/mcp.json"');
    assert.ok(result.includes('.gemini/settings.json'), 'Should contain ".gemini/settings.json"');
  });

  it('replaces claude --print with gemini --prompt', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('claude --print'), 'Should not contain "claude --print"');
    assert.ok(result.includes('gemini --prompt'), 'Should contain "gemini --prompt"');
  });

  it('replaces CLAUDE.local.md with GEMINI.local.md', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('CLAUDE.local.md'), 'Should not contain "CLAUDE.local.md"');
    assert.ok(result.includes('GEMINI.local.md'), 'Should contain "GEMINI.local.md"');
  });

  it('preserves non-replaced content', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.includes('# MyProject'));
    assert.ok(result.includes('## Pipeline'));
    assert.ok(result.includes('DISCOVER -> PLAN -> BUILD -> DEPLOY'));
  });
});

// ---------------------------------------------------------------------------
// generateAgentsMd
// ---------------------------------------------------------------------------

describe('generateAgentsMd', () => {
  it('replaces Claude Code with Codex CLI', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('Claude Code'), 'Should not contain "Claude Code"');
    assert.ok(result.includes('Codex CLI'), 'Should contain "Codex CLI"');
  });

  it('replaces CLAUDE.md with AGENTS.md', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    // The header legitimately contains "from CLAUDE.md" — strip it before checking
    const body = result.replace(/^<!--.*-->\n\n?/, '');
    assert.ok(!body.includes('CLAUDE.md'), 'Body should not contain "CLAUDE.md"');
    assert.ok(body.includes('AGENTS.md'), 'Body should contain "AGENTS.md"');
  });

  it('strips hook-related sections', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    // The ## Hooks and ## Hook System sections should be stripped
    assert.ok(!result.includes('## Hooks'), 'Should not contain "## Hooks" section');
    assert.ok(!result.includes('## Hook System'), 'Should not contain "## Hook System" section');
  });

  it('strips inline hook references', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    // "- **Hooks**: 6 Claude Code hooks active" should be stripped
    assert.ok(!result.includes('6 hooks'), 'Should strip hook bullet lines');
  });

  it('adds auto-generated header', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.startsWith('<!-- Auto-generated by chati.dev from CLAUDE.md'));
    assert.ok(result.includes('do not edit manually'));
  });

  it('replaces .claude/commands/ with chati.dev/orchestrator/ (Codex has no commands/)', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/commands/'), 'Should not contain ".claude/commands/"');
    assert.ok(result.includes('chati.dev/orchestrator/'), 'Should contain "chati.dev/orchestrator/"');
  });

  it('replaces .claude/rules/ with chati.dev/context/ (Codex has no rules/)', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/rules/'), 'Should not contain ".claude/rules/"');
    assert.ok(result.includes('chati.dev/context/'), 'Should contain "chati.dev/context/"');
  });

  it('replaces claude --print with codex exec', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('claude --print'), 'Should not contain "claude --print"');
    assert.ok(result.includes('codex exec'), 'Should contain "codex exec"');
  });

  it('replaces CLAUDE.local.md with AGENTS.local.md', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('CLAUDE.local.md'), 'Should not contain "CLAUDE.local.md"');
    assert.ok(result.includes('AGENTS.local.md'), 'Should contain "AGENTS.local.md"');
  });

  it('replaces .claude/mcp.json with .codex/config.toml', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/mcp.json'), 'Should not contain ".claude/mcp.json"');
    assert.ok(result.includes('.codex/config.toml'), 'Should contain ".codex/config.toml"');
  });

  it('does not leave triple blank lines after stripping', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('\n\n\n'), 'Should not have 3+ consecutive newlines');
  });

  it('preserves non-replaced, non-hook content', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.includes('# MyProject'));
    assert.ok(result.includes('## Pipeline'));
    assert.ok(result.includes('DISCOVER -> PLAN -> BUILD -> DEPLOY'));
  });
});
