name: Bug Report
description: Report a bug in Chati.dev
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        1. Run `...`
        2. Navigate to `...`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Chati.dev version
      description: "Run `npx chati-dev --version`"
      placeholder: "3.0.1"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      description: "Run `node -v`"
      placeholder: "v22.0.0"
    validations:
      required: true

  - type: dropdown
    id: ide
    attributes:
      label: IDE
      options:
        - Claude Code
        - VS Code
        - Cursor
        - Gemini CLI
        - GitHub Copilot
        - AntiGravity
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 15, Ubuntu 24, Windows 11"
    validations:
      required: true

  - type: textarea
    id: agent-context
    attributes:
      label: Agent Context (if applicable)
      description: Active agent, pipeline stage, session state.
      placeholder: |
        Active agent: Brief
        Pipeline stage: PLANNING
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or logs.
    validations:
      required: false
