name: Feature Request
description: Suggest an idea for Chati.dev
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What pain point does it address?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented.
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: New agent
        - label: Agent enhancement
        - label: CLI feature
        - label: Template/workflow
        - label: i18n
        - label: Documentation
        - label: Other

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've thought about.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, references, or examples.
    validations:
      required: false
